[toolchain]
channel = "nightly-2022-06-25"
components = [
    "clippy",
    "llvm-tools-preview",
    "rustfmt",
    "rust-src",
]
targets = [
    "x86_64-unknown-none",
    "aarch64-unknown-none-softfloat",
]
