[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-unknown-hermit-loader]
rustflags = [
  "-C", "link-arg=-Tsrc/arch/x86_64/link.ld"
]

[target.aarch64-unknown-hermit-loader]
rustflags = [
  "-C", "link-arg=-Tsrc/arch/aarch64/link.ld"
]

[target.riscv64imac-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tsrc/arch/riscv/link.ld"
]

[build]
target = "x86_64-unknown-hermit-loader.json"
